Updated addEdge
monkin77/FEUP-Projeto-CAL pull request #12
Opened 2021-05-07 22:01 UTC by BrunoRosendo

2021-05-08 17:05 UTC, monkin77 approved these changes

2021-05-08 19:43 UTC, monkin77 requested changes

2021-05-08 19:43 UTC, monkin77 commented on src/graph/Graph.cpp
> +    v2->addEdge(v1, weight);
We should do this on line 83 aswell (other addEdge function)

2021-05-12 14:40 UTC, up201906680 commented
Everything sounds ok! Gonna close this.

2021-05-12 14:42 UTC, up201906680 approved these changes
Everything's ok!

2021-05-12 14:51 UTC, monkin77 approved these changes
Me gusta

2021-05-12 14:53 UTC, merged